src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
#[ORM\HasLifecycleCallbacks()]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'string', length: 255)]
    private $image;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private $author;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, orphanRemoval: true)]
    private $comments;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'posts')]
    private $categories;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updated_at;
    

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    #[ORM\PrePersist]
    public function onPrePersist() {
        $date = new \DateTimeImmutable("now");
        $this->created_at = $date;
        $this->updated_at = $date;
    }

    #[ORM\PreUpdate]
    public function onPreUpdate() {
        $this->updated_at = new \DateTimeImmutable("now");
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Post;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', TextareaType::class)
            ->add('image', TextType::class)
            ->add('author', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'username',
            ])
            ->add('categories', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'label',
                'multiple' => true,
                'required' => false,
                // 'expanded' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\CommentType;
use App\Form\PostType;
use App\Repository\PostRepository;
use Doctrine\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @method User|null getUser()
 */
class PostController extends AbstractController
{
    #[Route('/posts', name: 'posts')]
    public function index(PostRepository $postRepository): Response
    {
        $posts = $postRepository->findAll();
        return $this->render('post/index.html.twig', [
            'posts' => $posts
        ]);
    }

    #[Route('/posts/{id}', name: 'post_detail')]
    public function detail(PostRepository $postRepository, Post $post): Response
    {
        $lastPosts = $postRepository->findBy([], ["id" => "DESC"], 3, 0);
        $form = $this->createForm(CommentType::class, null, ["action" => $this->generateUrl("comment_create", ["id" => $post->getId()])]);

        return $this->render('post/detail.html.twig', [
            'post' => $post,
            'last_posts' => $lastPosts,
            'form' => $form->createView()
        ]);
    }

    #[Route('/admin', name: 'admin')]
    #[Route('/author/posts', name: 'author')]
    #[IsGranted("ROLE_AUTHOR")]
    public function adminList(PostRepository $postRepository): Response
    {
        $user = $this->getUser();
        $posts = $this->isGranted("ROLE_ADMIN") ? $postRepository->findAll() : $postRepository->findBy(["author" => $user]);
        return $this->render('/admin/index.html.twig', [
            'posts' => $posts
        ]);
    }
    #[Route('/admin/posts/create', name: 'admin_post_create')]
    #[Route('/author/posts/create', name: 'author_post_create')]
    #[IsGranted("ROLE_AUTHOR")]
    public function createPost(Request $request, ManagerRegistry $doctrine): Response
    {
        $post = new Post();
        $user = $this->getUser();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager = $doctrine->getManager();
            if (!$this->isGranted("ROLE_ADMIN")) $post->setAuthor($user);
            $manager->persist($post);
            $manager->flush();
            return $this->redirect($this->generateUrl("admin"));
        } else if ($form->isSubmitted()) {
            $errors = array();
            foreach ($form as $formField) {
                $temp = array_filter(explode("\n", $formField->getErrors()->__toString()), fn (string $str) => !!strlen($str));
                $temp = array_map(fn (string $str) => str_replace("ERROR: ", "", $str), $temp);

                $errors = array_merge($errors, $temp);
            }
            array_map(fn (string $str) => $this->addFlash("danger", $str), $errors);
        }
    
        return $this->render('/admin/post.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/admin/posts/{id}/edit', name: 'admin_post_edit')]
    #[Route('/author/posts/{id}/edit', name: 'author_post_edit')]
    #[IsGranted("ROLE_AUTHOR")]
    public function editPost(Request $request, ManagerRegistry $doctrine, Post $post): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager = $doctrine->getManager();
            if (!$this->isGranted("ROLE_ADMIN")) {
                $post->setAuthor($user);
                $manager->flush();
                return $this->redirect($this->generateUrl("author"));
            } else {
                $manager->flush();
                return $this->redirect($this->generateUrl("admin"));
            }
        } else if ($form->isSubmitted()) {
            $errors = array();
            foreach ($form as $formField) {
                $temp = array_filter(explode("\n", $formField->getErrors()->__toString()), fn (string $str) => !!strlen($str));
                $temp = array_map(fn (string $str) => str_replace("ERROR: ", "", $str), $temp);

                $errors = array_merge($errors, $temp);
            }
            array_map(fn (string $str) => $this->addFlash("danger", $str), $errors);
        }
    
        return $this->render('/admin/post.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/admin/posts/{id}/delete', name: 'admin_post_delete')]
    #[Route('/author/posts/{id}/delete', name: 'author_post_delete')]
    #[IsGranted("ROLE_AUTHOR")]
    public function deletePost(ManagerRegistry $doctrine, Post $post): Response
    {
        $user = $this->getUser();
        if (!$this->isGranted("ROLE_ADMIN") && $user->getId() !== $post->getAuthor()->getId()) {
            return $this->redirect($this->generateUrl("author"));
        }
        $manager = $doctrine->getManager();
        $manager->remove($post);
        $manager->flush();

        return $this->redirect($this->generateUrl("admin"));
    }
}

templates/post/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recette | {{ post.title }}
{% endblock %}

{% block body %}
	<div class="container post">
		<div class="post-container">
			<div class="post-author">
				<i class="fa-solid fa-user"></i>
				{{ post.author.username }}
				• Le
				{{ post.createdAt|date("d/m/Y") }}
				•
				{% for category in post.categories %}
					{{ category.label }}
				{% endfor %}
			</div>
			<div class="post-title">
				{{ post.title }}
			</div>
			<img src="{{ post.image }}">
			<p class="post-content">
				{{ post.content }}
			</p>
			<hr class="divider medium">
			<div class="post-comments">
				<i class="fa-solid fa-comment"></i>
				{{ post.comments|length }}
				commentaires
				<div class="comments">
					{% for comment in post.comments %}
						<div class="comment">
							<div class="comment-title">
								Rédigé par
								{% if comment.author %}
									{{ comment.author.username }}, le
								{% else %}
									{{ comment.username }}, le
								{% endif %}
								{{ comment.createdAt|date("d/m/Y H:i") }}
								{% if 
									is_granted('ROLE_ADMIN') or 
									(is_granted('ROLE_AUTHOR') and app.user.id == post.author.id) or
									(comment.author and app.user and (comment.author.id == app.user.id))
								%}
									<a href="{{ path("comment_delete", {id: comment.id}) }}">Supprimer</a>
								{% endif %}
							</div>
							<div class="comment-body">
								{{ comment.content }}
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
			<div class="new-comment">
				<h6>Laisser un commentaire</h6>


				{{ form_start(form) }}
				{% if is_granted('ROLE_USER') %}
					{% do form.username.setRendered() %}
				{% else %}
					{{ form_row(form.username, {attr: {required: true}}) }}
				{% endif %}
				{{ form_row(form.content) }}

				<button type="submit" class="btn btn-primary">Envoyer</button>
				{{ form_end(form) }}
			</div>
		<div class="last-posts">
			<h6>Recettes récentes</h6>
			<div class="grid">
				{% for post in last_posts %}
					<div class="card">
						<img src="{{ post.image }}">
						<div class="card-body">
							<div class="card-title">
								{{ post.title }}
							</div>
							<p class="card-content">
								{{ post.content }}
							</p>
							<a href="{{ path("post_detail", {id: post.id}) }}" class="btn btn-primary">Voir plus</a>
							<hr class="divider medium">
							<div class="card-comments">
								<i class="fa-solid fa-comment"></i>
								{{ post.comments|length }}
								commentaires
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recettes
{% endblock %}

{% block body %}
	<div class="container posts">
		{% for post in posts %}
			<div class="card">
				<img src="{{ post.image }}">
				<div class="card-body">
					<div class="card-author">
						<i class="fa-solid fa-user"></i>
						{{ post.author.username }}
						• Le
						{{ post.createdAt|date("d/m/Y") }}
						•
						{% for category in post.categories %}
							{{ category.label }}
						{% endfor %}
					</div>
					<div class="card-title">
						{{ post.title }}
					</div>
					<p class="card-content">
						{{ post.content }}
					</p>
					<a href="{{ path("post_detail", {id: post.id}) }}" class="btn btn-primary">Voir plus</a>
					<hr class="divider medium">
					<div class="card-comments">
						<i class="fa-solid fa-comment"></i>
						{{ post.comments|length }}
						commentaires
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}